<?php
$page = [
 'title'=>'Air Quality Testing West Vancouver - (604)800-3900','description'=>'Indoor air quality testing in West Vancouver for mold related concerns, musty odours and water-damaged properties. Call (604)800-3900.','path'=>'air-quality-testing','breadcrumb'=>'Air Quality Testing','eyebrow'=>'Indoor air assessment • West Vancouver','h1'=>'Air Quality Testing in <em>West Vancouver</em>','lead'=>'Investigate mold related indoor air concerns using targeted sampling and building observations, not numbers without context.','hero_image'=>'image/how-air-quality-testing.webp','hero_alt'=>'Indoor air quality testing equipment used for a mold investigation','hero_points'=>['Targeted air sampling','Indoor and outdoor context','Plain language findings'],
 'intro_kicker'=>'A building and air investigation','intro_heading'=>'What mold related air testing can show','intro_paragraphs'=>['Air sampling can provide a snapshot of airborne fungal particles at a particular place and time. It can be useful when occupants report a musty odour, concealed impact is suspected or documentation is needed after water damage. It does not replace a visual inspection or moisture investigation.','Results can change with weather, ventilation, windows, cleaning and activity in the room. Comparison samples and a clear sampling plan are important because a single indoor number has limited meaning on its own.','A useful assessment combines air results with the building history, visible conditions and moisture measurements. This helps West Vancouver property owners understand whether the findings support further investigation or corrective work.'],
 'concerns_kicker'=>'When sampling may help','concerns_heading'=>'Questions air quality testing may support','concerns_intro'=>['The sampling plan should be designed around a specific concern. More samples do not automatically create a better answer.','Health diagnosis is outside the scope of property testing; medical questions should be discussed with a qualified healthcare provider.'],
 'concerns'=>[['Musty odour with no visible source','Air sampling may add context when inspection does not reveal where an odour originates.'],['Concern after water damage','Sampling can be considered when materials were wet and the adequacy of drying or cleanup is uncertain.'],['Condo or strata documentation','Results may support communication when the suspected source extends beyond one accessible unit.'],['Commercial occupied spaces','A documented plan can help investigate a concern while considering HVAC zones and business operations.'],['Post remediation verification','Independent assessment may be appropriate when a project scope requires documented conditions after cleanup.'],['Comparison between areas','Samples from suspect, unaffected and outdoor locations can provide more useful context than one isolated result.']],
 'process_heading'=>'A targeted air quality testing process','process_intro'=>'Sampling is planned after the purpose, property conditions and relevant comparison areas are understood.','steps'=>[['Clarify the question','Discuss odours, water history, rooms involved, occupant observations and how the results will be used.'],['Inspect the environment','Review visible conditions, moisture indicators, ventilation and activities that could influence the sample.'],['Collect appropriate samples','Use selected indoor and comparison locations with consistent procedures and clear documentation.'],['Interpret in context','Review laboratory findings alongside the property observations and explain practical next steps.']],
 'secondary_image'=>'image/mold-house.webp','secondary_alt'=>'Indoor wall affected by moisture and mold near a window','detail_kicker'=>'Avoid number only conclusions','detail_heading'=>'Air results need building context','detail_paragraphs'=>['There is no single universal indoor mold number that answers every property question. The types and relative distribution of particles, outdoor conditions, room use and evidence of moisture all matter.','A result should be used to support investigation and decision making, not to create certainty beyond what the sampling method can provide. Limitations and conditions at the time of sampling should be documented.'],'detail_points'=>['Review indoor and outdoor conditions','Record ventilation and window status','Consider recent cleaning or construction','Connect results with moisture observations'],
 'local_heading'=>'Indoor air quality testing in West Vancouver','local_paragraphs'=>['Coastal humidity, seasonal rain, tightly closed homes and varied ventilation systems can all affect indoor conditions. Sampling plans are adapted to the property rather than using the same locations for every job.','Testing is available for homes, condos, offices and managed properties throughout West Vancouver.'],
 'faq_heading'=>'Air quality testing questions','faqs'=>[['Can an air test prove a room is completely mold free?','No. Air testing is a limited snapshot and cannot prove the absence of all mold. Results should be considered with inspection and moisture findings.'],['Should windows be open during testing?','Sampling conditions depend on the purpose. Window and HVAC status should be consistent with the plan and recorded because they can affect results.'],['How many samples are needed?','The number depends on the property layout, areas of concern and comparison strategy. A targeted plan is preferable to an arbitrary sample count.'],['Does air testing diagnose health problems?','No. Property testing does not diagnose medical conditions. Discuss symptoms and health concerns with a qualified healthcare provider.'],['Can testing be done after remediation?','Yes, when post remediation assessment is part of the project plan. Independence, timing and acceptance criteria should be established before testing.']]
];
require __DIR__ . '/service-page.php';
