<?php
$page = [
 'title'=>'Black Mold Inspection West Vancouver - (604)800-3900','description'=>'Black mold inspection in West Vancouver for dark growth, water damage and musty odours. Get a careful property assessment. Call (604)800-3900.','path'=>'black-mold-inspection','breadcrumb'=>'Black Mold Inspection','eyebrow'=>'Dark mold concerns • West Vancouver','h1'=>'Black Mold Inspection in <em>West Vancouver</em>','lead'=>'Get a measured assessment of dark or black coloured growth without relying on colour alone to identify the problem.','hero_image'=>'image/mold-wall.webp','hero_alt'=>'Dark mold growth on an interior wall requiring inspection','hero_points'=>['Careful visual assessment','Moisture source investigation','Testing when it adds value'],
 'intro_kicker'=>'Colour is not identification','intro_heading'=>'What a black mold inspection should determine','intro_paragraphs'=>['Many types of mold can appear black, dark green or brown. Colour alone cannot identify a species or determine the level of risk. A useful inspection focuses first on the amount of affected material, the moisture conditions, the location and whether the growth may extend into a concealed space.','The phrase “black mold” often creates understandable concern. The best response is calm and evidence based: avoid disturbing the material, identify why the area became damp and decide whether sampling would change the remediation plan.','For West Vancouver properties, dark growth may appear near windows, exterior corners, basements, roof spaces or areas affected by plumbing and building envelope leaks. Each pattern calls for a different investigation.'],
 'concerns_kicker'=>'What we look for','concerns_heading'=>'Important factors beyond the colour','concerns_intro'=>['The same dark appearance can occur on different materials for different reasons. Inspection helps separate surface condensation issues from deeper water damage and concealed impact.','The scope of affected material and the cause of moisture are usually more important to the remediation plan than the colour alone.'],
 'concerns'=>[['Area and location','A small window edge patch is different from widespread growth across drywall, sheathing or framing.'],['Material condition','Porous materials that are damaged or deeply colonized may require removal rather than surface cleaning.'],['Moisture source','Roof leaks, plumbing, foundation moisture and condensation require different corrective work.'],['Hidden extension','Visible growth at a seam, baseboard or ceiling edge may continue behind the finished surface.'],['Occupancy and access','Bedrooms, rental units and shared strata areas may require additional planning and documentation.'],['Disturbance risk','Brushing, sanding or removing affected material can release particles and should not begin without a plan.']],
 'process_heading'=>'A calm, evidence based inspection','process_intro'=>'The inspection documents visible conditions, investigates moisture and recommends testing only when the result may clarify the scope or next step.','steps'=>[['Describe what changed','Review when the dark growth appeared, whether it returns and any known leak or condensation history.'],['Inspect the affected area','Document the size, material, location and nearby signs of water movement or damage.'],['Check for moisture','Compare the suspect area with surrounding materials and consider likely pathways into the assembly.'],['Define the response','Explain whether cleaning, targeted testing, controlled removal or further building investigation may be appropriate.']],
 'secondary_image'=>'image/mold-in-corner-door-vancouver.webp','secondary_alt'=>'Black-coloured mold around the corner of a doorway','detail_kicker'=>'Do not disturb it first','detail_heading'=>'Protect the area while you arrange an inspection','detail_paragraphs'=>['Avoid sanding, dry brushing or cutting into suspect material. These actions can spread dust and make the original extent harder to document. If there is an active leak, address the water source safely and keep people away from damaged materials.','Photographs and a short timeline are useful. Note recent storms, plumbing issues, renovations, ventilation changes or periods when the home was closed up. This information can help connect visible growth with the conditions that produced it.'],'detail_points'=>['Do not paint over suspect growth','Avoid dry scraping or sanding','Stop active water entry when safe','Keep records of leaks and changes'],
 'local_heading'=>'Black mold concerns in West Vancouver homes','local_paragraphs'=>['Coastal rain, shaded walls, complex rooflines and cold exterior corners can all influence moisture in West Vancouver buildings. The assessment considers those local conditions without assuming that every dark mark has the same cause.','Service is available throughout West Vancouver for houses, condos, strata properties and commercial spaces.'],
 'faq_heading'=>'Black mold inspection questions','faqs'=>[['Can you identify black mold by looking at it?','No. Colour and appearance are not enough to identify a mold species. Laboratory analysis is required for identification when that information is necessary.'],['Is all black coloured mold the same?','No. Many molds can appear dark, and other staining can also look similar. Inspection focuses on moisture, material condition and extent.'],['Should I clean the area before an inspection?','It is usually better not to disturb or clean the suspect area first. Photographs and undisturbed conditions can provide useful context.'],['Will testing always be required?','No. Testing is recommended when it is likely to answer a specific question or affect the next step. Visible impact and moisture may already be enough to plan corrective work.'],['Do you inspect dark mold in West Vancouver condos?','Yes. Condo inspections consider the unit, adjacent assemblies and possible strata responsibilities.']]
];
require __DIR__ . '/service-page.php';
