<?php
$page = [
 'title'=>'Condo Mold Inspection West Vancouver - (604) 800-3900','description'=>'Condo mold inspection in West Vancouver for leaks, window condensation, musty odours and strata moisture concerns. Call (604) 800-3900.','path'=>'condo-mold-inspection','breadcrumb'=>'Condo Mold Inspection','eyebrow'=>'Condo and strata assessment • West Vancouver','h1'=>'Condo Mold Inspection in <em>West Vancouver</em>','lead'=>'Document moisture and mold concerns inside a condo while considering neighbouring units and common building systems.','hero_image'=>'image/mold-in-corner-door-vancouver.webp','hero_alt'=>'Mold growth in the corner of a condominium interior','hero_points'=>['Unit specific inspection','Strata context considered','Clear photo documentation'],
 'intro_kicker'=>'A shared building context','intro_heading'=>'Mold concerns in West Vancouver condos','intro_paragraphs'=>['A mold concern inside a condo may originate within the unit, from a neighbouring unit or from a common building component. Plumbing stacks, exterior walls, windows, roofs, balconies and shared mechanical systems can all influence where moisture appears.','The inspection documents conditions inside the accessible unit and considers the pattern of damage. Clear notes and photographs can help owners, tenants, property managers and strata representatives understand what further access or repair may be needed.','Condensation is also common around windows, exterior corners and rooms with limited ventilation. It is important to distinguish recurring indoor humidity from a building envelope or plumbing leak before deciding on remediation.'],
 'concerns_kicker'=>'Common condo concerns','concerns_heading'=>'Where moisture may appear in a condo','concerns_intro'=>['Condo investigations benefit from a timeline. Building notices, previous repairs, neighbouring unit events and seasonal weather can help explain the source.','The inspection remains focused on accessible areas and clearly identifies when strata or another professional must investigate beyond the unit.'],
 'concerns'=>[['Windows and exterior corners','Condensation, seal failures and exterior water entry can create similar looking stains near the perimeter.'],['Bathrooms and laundry areas','Exhaust, supply lines, drains and appliance connections can contribute to hidden moisture.'],['Ceilings below other units','Water may travel from plumbing, balconies or fixtures in the unit above.'],['Shared plumbing walls','Leaks around stacks and supply lines can affect more than one suite and require coordinated access.'],['Closets on outside walls','Low air circulation and cool wall surfaces can allow condensation behind stored contents.'],['Balcony and envelope interfaces','Doors, membranes and wall penetrations may require building envelope review when leaks recur.']],
 'process_heading'=>'A condo focused inspection process','process_intro'=>'Documentation and communication are especially important when responsibility or access extends beyond one unit.','steps'=>[['Build the timeline','Record when the issue appeared, weather or plumbing events, prior repairs and strata communication.'],['Inspect the unit','Review visible damage, moisture patterns, ventilation and accessible materials in the affected rooms.'],['Consider shared sources','Assess whether the pattern points toward an in unit source, neighbouring unit or common property.'],['Document next steps','Provide clear observations for remediation planning and any recommended strata, plumbing or envelope follow up.']],
 'secondary_image'=>'image/mold-in-kitchen.webp','secondary_alt'=>'Moisture and mold concern inside a condominium kitchen','detail_kicker'=>'Useful documentation','detail_heading'=>'Clear findings help coordinate the response','detail_paragraphs'=>['A concise record of affected locations, moisture readings, photographs and relevant history can reduce confusion between occupants, owners and strata representatives. It does not determine legal responsibility, but it can clarify what was observed and what additional investigation is reasonable.','If the moisture source is outside the unit, remediation inside the suite should be coordinated with source repair. Rebuilding too early can conceal continued water entry and lead to repeated damage.'],'detail_points'=>['Record affected rooms and materials','Photograph visible conditions','Note moisture and ventilation patterns','Identify recommended specialist follow up'],
 'local_heading'=>'Condo mold inspections across West Vancouver','local_paragraphs'=>['West Vancouver includes older low rise buildings, concrete towers, waterfront developments and newer strata communities. Each building type has different envelope, ventilation and plumbing considerations.','We provide unit focused inspections throughout West Vancouver and communicate the findings in language owners and property managers can use.'],
 'faq_heading'=>'Condo mold inspection questions','faqs'=>[['Is condo mold the owner’s or strata’s responsibility?','Responsibility depends on the source, location, governing documents and applicable decisions. An inspection documents conditions but does not provide a legal determination.'],['Should I notify strata before the inspection?','It is often helpful, especially when access to common property, plumbing or another unit may be required. Keep copies of relevant notices and repair records.'],['Can window condensation cause mold?','Yes. Repeated condensation can wet frames, drywall and nearby contents. The cause may involve indoor humidity, ventilation, window performance or exterior conditions.'],['Can you inspect without entering another unit?','The accessible unit can be assessed, but limitations are documented. Some sources cannot be confirmed without coordinated access.'],['Do you inspect rental condos?','Yes. Owners, tenants or property managers can arrange an inspection, subject to appropriate access authorization.']]
];
require __DIR__ . '/service-page.php';
