<?php
$page = [
 'title'=>'Crawl Space Mold Inspection West Vancouver - (604)800-3900','description'=>'Crawl space mold inspection in West Vancouver for damp wood, musty odours, foundation moisture and plumbing leaks. Call (604)800-3900.','path'=>'crawl-space-mold-inspection','breadcrumb'=>'Crawl Space Mold Inspection','eyebrow'=>'Below floor moisture review • West Vancouver','h1'=>'Crawl Space Mold Inspection in <em>West Vancouver</em>','lead'=>'Assess damp framing, foundation moisture and musty conditions beneath your home before damage progresses.','hero_image'=>'image/mold-ground-floor.webp','hero_alt'=>'Moisture and mold conditions in a residential crawl space','hero_points'=>['Accessible framing assessment','Foundation moisture review','Drainage and ventilation context'],
 'intro_kicker'=>'Moisture below the home','intro_heading'=>'Why crawl spaces develop mold','intro_paragraphs'=>['Crawl spaces are vulnerable to ground moisture, drainage problems, plumbing leaks and humid outdoor air. Because they are out of sight, damp conditions can continue for long periods before odours, pests or floor changes are noticed inside the home.','West Vancouver sites can be steep, shaded and exposed to extended rainfall. Surface drainage, foundation details and seasonal groundwater can influence the moisture level below a house. Vent openings alone do not always keep a crawl space dry.','An inspection looks at accessible wood framing, insulation, foundation walls, soil or ground cover, plumbing and signs of water movement. The goal is to connect visible mold or staining with the source that must be corrected.'],
 'concerns_kicker'=>'Signs below the floor','concerns_heading'=>'Crawl space conditions to investigate','concerns_intro'=>['A musty crawl space can affect stored materials and may indicate moisture reaching structural wood. Changes should be assessed before installing new insulation or covering surfaces.','Safety and access matter. Low clearances, electrical hazards, pests and deteriorated materials may limit the accessible inspection area.'],
 'concerns'=>[['White or dark growth on wood','Visible spotting or fuzzy growth on joists and subflooring can indicate sustained dampness.'],['Standing water or wet soil','Puddles, seepage and saturated ground increase humidity and can wet adjacent materials.'],['Missing ground cover','Exposed damp soil can release significant moisture into an enclosed crawl space.'],['Plumbing leakage','Slow supply, drain or appliance leaks may affect insulation and framing without obvious signs upstairs.'],['Sagging insulation','Wet, displaced or contaminated insulation can hide the condition of the subfloor and joists.'],['Musty indoor odours','Air movement from the crawl space can carry odours through gaps and service penetrations.']],
 'process_heading'=>'A crawl space inspection process','process_intro'=>'The inspection follows visible water paths and building details while respecting safe access limitations.','steps'=>[['Review seasonal patterns','Discuss odours, flooding, drainage work, plumbing history and when the issue is most noticeable.'],['Inspect accessible areas','Check framing, subfloor, insulation, foundation surfaces, penetrations and the condition of the ground.'],['Identify moisture contributors','Consider drainage, seepage, evaporation, ventilation, plumbing and exterior grading.'],['Develop priorities','Separate immediate water control needs from remediation, insulation and longer term crawl space improvements.']],
 'secondary_image'=>'image/mold-ground-floor.webp','secondary_alt'=>'Dark moisture staining beneath the floor of a West Vancouver home','detail_kicker'=>'Control water and humidity','detail_heading'=>'Remediation starts with a drier crawl space','detail_paragraphs'=>['Cleaning visible growth without changing the damp environment can lead to recurrence. Drainage, plumbing, ground cover, air sealing and humidity management may all play a role, depending on the crawl space design.','Affected insulation and debris can obstruct the inspection and may need controlled removal. Sound structural wood and damaged material should be evaluated separately so the work plan addresses both contamination and building performance.'],'detail_points'=>['Stop active plumbing leaks','Improve exterior water management','Use an appropriate ground moisture barrier','Assess damaged insulation and wood'],
 'local_heading'=>'Crawl space inspections in West Vancouver','local_paragraphs'=>['Hillside runoff, shaded foundations and older construction details are common local considerations. The inspection takes the site and building layout into account instead of treating every crawl space the same.','Service is available for accessible crawl spaces throughout West Vancouver, including older homes and renovated properties.'],
 'faq_heading'=>'Crawl space mold questions','faqs'=>[['Why does my crawl space smell musty?','Musty odours commonly relate to damp soil, wet wood, contaminated insulation or stagnant moisture. An inspection helps identify the contributors.'],['Will adding vents solve crawl space moisture?','Not always. Outdoor air can add humidity during some conditions, and vents do not correct leaks, drainage problems or exposed damp soil.'],['Can crawl space mold affect the home above?','Air can move through plumbing, wiring and framing gaps. The degree of connection depends on the building, so both crawl space conditions and air pathways should be considered.'],['Do I need to remove crawl space insulation?','Insulation that is wet, damaged, contaminated or blocking access may need removal. Clean, dry and properly installed material may be retained.'],['Can you inspect a very low crawl space?','Access depends on clearance and safety. Any inaccessible areas or limitations should be documented, and other investigation methods may be discussed.']]
];
require __DIR__ . '/service-page.php';
